# Generated by Django 4.2.14 on 2024-08-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsapi', '0002_pet_description_alter_pet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pettype',
            field=models.CharField(choices=[('dog', 'DOG'), ('cat', 'CAT'), ('bird', 'BIRD'), ('fish', 'FISH'), ('reptile', 'REPTILE'), ('hamster', 'HAMSTER')], default='dog', max_length=100),
        ),
    ]
