# Generated by Django 4.2.14 on 2024-08-05 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petsapi', '0003_alter_pet_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='owner',
        ),
    ]
