# Generated by Django 4.2.14 on 2024-08-16 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petsapi', '0006_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='pets',
        ),
        migrations.AddField(
            model_name='pet',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='petsapi.cart'),
        ),
    ]
