# Generated by Django 4.2.14 on 2024-08-17 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petsapi', '0008_alter_pet_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='petsapi.cart'),
        ),
    ]
